name = 'not-much'
license = 'MIT'
licenselink = 'https://github.com/imgios/not-much/blob/main/LICENSE'
description = 'A minimal blog theme for Hugo'

homepage = 'https://github.com/imgios/not-much'

demosite = 'https://giosuesulipano.it/not-much/'

tags = ['blog', 'website', 'simple', 'dark', 'minimal', 'responsive']

features = ['blog', 'reponsive', 'theme-palettes']

[author]
  name = 'Giosuè Sulipano'
  homepage = 'https://giosuesulipano.it'

[module]
  [[module.mounts]]
    source = "./node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

  [[module.mounts]]
    source = "./node_modules/bootstrap/dist/css"
    target = "assets/css/bootstrap"
    
  [[module.mounts]]
    source = "./node_modules/@fontsource-variable"
    target = "assets/fonts"
